//
// Generated file, do not edit! Created by nedtool 4.6 from src/VLCnode/VLCpacket.msg.
//

#ifndef _VLCPACKET_M_H_
#define _VLCPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/VLCnode/VLCpacket.msg:16</tt> by nedtool.
 * <pre>
 * packet VLCpacket
 * {
 *     string content;
 * }
 * </pre>
 */
class VLCpacket : public ::cPacket
{
  protected:
    opp_string content_var;

  private:
    void copy(const VLCpacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const VLCpacket&);

  public:
    VLCpacket(const char *name=NULL, int kind=0);
    VLCpacket(const VLCpacket& other);
    virtual ~VLCpacket();
    VLCpacket& operator=(const VLCpacket& other);
    virtual VLCpacket *dup() const {return new VLCpacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getContent() const;
    virtual void setContent(const char * content);
};

inline void doPacking(cCommBuffer *b, VLCpacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, VLCpacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _VLCPACKET_M_H_

