//
// Generated file, do not edit! Created by nedtool 4.6 from src/VLCnode/VLCmobilityManager/VLCmobilityMsg.msg.
//

#ifndef _VLCMOBILITYMSG_M_H_
#define _VLCMOBILITYMSG_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/VLCnode/VLCmobilityManager/VLCmobilityMsg.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message VLCmobilityMsg
 * {
 * }
 * </pre>
 */
class VLCmobilityMsg : public ::cMessage
{
  protected:

  private:
    void copy(const VLCmobilityMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const VLCmobilityMsg&);

  public:
    VLCmobilityMsg(const char *name=NULL, int kind=0);
    VLCmobilityMsg(const VLCmobilityMsg& other);
    virtual ~VLCmobilityMsg();
    VLCmobilityMsg& operator=(const VLCmobilityMsg& other);
    virtual VLCmobilityMsg *dup() const {return new VLCmobilityMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, VLCmobilityMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, VLCmobilityMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _VLCMOBILITYMSG_M_H_

